apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: myappp
    owner: angel
spec:
  containers:
  - name: db
    image: mysql
    env:
      - name: "MYSQL_ROOT_PASSWORD"
        value: "Pass123!"
      - name: "MYSQL_PASSWORD"
        value: "Pass123!"
      - name: "MYSQL_USER"
        value: "wpuser"
      - name: "MYSQL_DATABASE"
        value: "wpdb"