apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: myappp
spec:
  containers:
  - name: wp
    image: wordpress
    env:
      - name: "WORDPRESS_DB_HOST" 
        value: "mysqlsvc"
      - name: "WORDPRESS_DB_USER"
        value: "wpuser"
      - name: "WORDPRESS_DB_PASSWORD"
        value: "Pass123!"
      - name: "WORDPRESS_DB_NAME"
        value: "wpdb" 
    ports: 
      - containerPort: 80