apiVersion: v1
kind: Pod
metadata:
  name: demowp
spec:
  containers:
  - name: wp
    image: wordpress
    env:
      - name: "WORDPRESS_DB_HOST" 
        value: 127.0.0.1
      - name: "WORDPRESS_DB_USER"
        value: "wpuser"
      - name: "WORDPRESS_DB_PASSWORD"
        value: "Pass123!"
      - name: "WORDPRESS_DB_NAME"
        value: "wpdb" 
    ports: 
      - containerPort: 80  
  - name: db
    image: mysql
    env:
      - name: "MYSQL_ROOT_PASSWORD"
        value: "Pass123!"
      - name: "MYSQL_PASSWORD"
        value: "Pass123!"
      - name: "MYSQL_USER"
        value: "wpuser"
      - name: "MYSQL_DATABASE"
        value: "wpdb"