apiVersion: v1
kind: ReplicationController
metadata:
  name: api
spec:
  replicas: 5
  selector:
    app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: main
          image: lemoncodersbc/go-hello-world
          ports:
            - containerPort: 80